/* Generated by tools/delta-consts.py. Do not edit.

   Bytes a rule of ours names by address, out of lang/hien/rules/constants.
   The lifted ones are in delta_consts_hien.c, generated out of IBM's
   objects; these are kept apart so that running that lifter again cannot lose
   them.

   Everything here is copied into the arena at startup beside the lifted
   stores, because the machine holds addresses in thirty-two bit values and an
   address in the program is not one of those. */

#include <stdint.h>

#include "delta_lang.h"

uint8_t hien_evv_authored_data[] = {
    /* hi_k, 1 bytes at 0 */
    7,
    /* hi_kh, 1 bytes at 1 */
    7,
    /* hi_g, 1 bytes at 2 */
    8,
    /* hi_gh, 1 bytes at 3 */
    8,
    /* hi_ng, 1 bytes at 4 */
    22,
    /* hi_c, 1 bytes at 5 */
    18,
    /* hi_ch, 1 bytes at 6 */
    18,
    /* hi_j, 1 bytes at 7 */
    17,
    /* hi_jh, 1 bytes at 8 */
    17,
    /* hi_ny, 1 bytes at 9 */
    21,
    /* hi_tt, 1 bytes at 10 */
    4,
    /* hi_tth, 1 bytes at 11 */
    4,
    /* hi_dd, 1 bytes at 12 */
    3,
    /* hi_ddh, 1 bytes at 13 */
    3,
    /* hi_nn, 1 bytes at 14 */
    21,
    /* hi_t, 1 bytes at 15 */
    4,
    /* hi_th, 1 bytes at 16 */
    4,
    /* hi_d, 1 bytes at 17 */
    3,
    /* hi_dh, 1 bytes at 18 */
    3,
    /* hi_n, 1 bytes at 19 */
    21,
    /* hi_p, 1 bytes at 20 */
    2,
    /* hi_ph, 1 bytes at 21 */
    12,
    /* hi_b, 1 bytes at 22 */
    1,
    /* hi_bh, 1 bytes at 23 */
    1,
    /* hi_m, 1 bytes at 24 */
    20,
    /* hi_y, 1 bytes at 25 */
    26,
    /* hi_r, 1 bytes at 26 */
    24,
    /* hi_l, 1 bytes at 27 */
    25,
    /* hi_v, 1 bytes at 28 */
    11,
    /* hi_sh, 1 bytes at 29 */
    16,
    /* hi_ssh, 1 bytes at 30 */
    16,
    /* hi_s, 1 bytes at 31 */
    14,
    /* hi_h, 1 bytes at 32 */
    19,
    /* hi_ka, 2 bytes at 33 */
    7,44,
    /* hi_kha, 2 bytes at 35 */
    7,44,
    /* hi_ga, 2 bytes at 37 */
    8,44,
    /* hi_gha, 2 bytes at 39 */
    8,44,
    /* hi_nga, 2 bytes at 41 */
    22,44,
    /* hi_ca, 2 bytes at 43 */
    18,44,
    /* hi_cha, 2 bytes at 45 */
    18,44,
    /* hi_ja, 2 bytes at 47 */
    17,44,
    /* hi_jha, 2 bytes at 49 */
    17,44,
    /* hi_nya, 2 bytes at 51 */
    21,44,
    /* hi_tta, 2 bytes at 53 */
    4,44,
    /* hi_ttha, 2 bytes at 55 */
    4,44,
    /* hi_dda, 2 bytes at 57 */
    3,44,
    /* hi_ddha, 2 bytes at 59 */
    3,44,
    /* hi_nna, 2 bytes at 61 */
    21,44,
    /* hi_ta, 2 bytes at 63 */
    4,44,
    /* hi_tha, 2 bytes at 65 */
    4,44,
    /* hi_da, 2 bytes at 67 */
    3,44,
    /* hi_dha, 2 bytes at 69 */
    3,44,
    /* hi_na, 2 bytes at 71 */
    21,44,
    /* hi_pa, 2 bytes at 73 */
    2,44,
    /* hi_pha, 2 bytes at 75 */
    12,44,
    /* hi_ba, 2 bytes at 77 */
    1,44,
    /* hi_bha, 2 bytes at 79 */
    1,44,
    /* hi_ma, 2 bytes at 81 */
    20,44,
    /* hi_ya, 2 bytes at 83 */
    26,44,
    /* hi_ra, 2 bytes at 85 */
    24,44,
    /* hi_la, 2 bytes at 87 */
    25,44,
    /* hi_va, 2 bytes at 89 */
    11,44,
    /* hi_sha, 2 bytes at 91 */
    16,44,
    /* hi_ssha, 2 bytes at 93 */
    16,44,
    /* hi_sa, 2 bytes at 95 */
    14,44,
    /* hi_ha, 2 bytes at 97 */
    19,44,
    /* hi_a, 1 bytes at 99 */
    44,
    /* hi_aa, 1 bytes at 100 */
    42,
    /* hi_i, 1 bytes at 101 */
    28,
    /* hi_ii, 1 bytes at 102 */
    29,
    /* hi_u, 1 bytes at 103 */
    45,
    /* hi_uu, 1 bytes at 104 */
    46,
    /* hi_ri, 2 bytes at 105 */
    24,28,
    /* hi_e, 1 bytes at 107 */
    30,
    /* hi_ai, 1 bytes at 108 */
    31,
    /* hi_o, 1 bytes at 109 */
    47,
    /* hi_au, 1 bytes at 110 */
    51,
    /* hi_anu, 1 bytes at 111 */
    21,
    /* hi_visg, 1 bytes at 112 */
    19,
    /* hi_virama_char, 1 bytes at 113 */
    204,
    /* hi_matra_chars, 10 bytes at 114 */
    191,192,193,194,195,196,197,198,199,200,
};

const delta_store hien_delta_authored_store[] = {
    { hien_evv_authored_data, sizeof hien_evv_authored_data },
    { 0, 0 },
};
